// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.4
// source: rpc/doc/registeration.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 坐诊医生列表展示
type AttendingPhysician struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AttendingPhysician) Reset() {
	*x = AttendingPhysician{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_doc_registeration_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttendingPhysician) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttendingPhysician) ProtoMessage() {}

func (x *AttendingPhysician) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_doc_registeration_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttendingPhysician.ProtoReflect.Descriptor instead.
func (*AttendingPhysician) Descriptor() ([]byte, []int) {
	return file_rpc_doc_registeration_proto_rawDescGZIP(), []int{0}
}

// 预约  增删改查
type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_doc_registeration_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_doc_registeration_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_rpc_doc_registeration_proto_rawDescGZIP(), []int{1}
}

type AddAppointmentRegisterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PatientId       int32  `protobuf:"varint,10,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	DoctorId        int32  `protobuf:"varint,20,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	RealName        string `protobuf:"bytes,30,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	IdNumber        string `protobuf:"bytes,40,opt,name=id_number,json=idNumber,proto3" json:"id_number,omitempty"`
	Mobile          string `protobuf:"bytes,50,opt,name=mobile,proto3" json:"mobile,omitempty"`
	AppointmentTime string `protobuf:"bytes,60,opt,name=appointment_time,json=appointmentTime,proto3" json:"appointment_time,omitempty"`
}

func (x *AddAppointmentRegisterReq) Reset() {
	*x = AddAppointmentRegisterReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_doc_registeration_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddAppointmentRegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAppointmentRegisterReq) ProtoMessage() {}

func (x *AddAppointmentRegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_doc_registeration_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAppointmentRegisterReq.ProtoReflect.Descriptor instead.
func (*AddAppointmentRegisterReq) Descriptor() ([]byte, []int) {
	return file_rpc_doc_registeration_proto_rawDescGZIP(), []int{2}
}

func (x *AddAppointmentRegisterReq) GetPatientId() int32 {
	if x != nil {
		return x.PatientId
	}
	return 0
}

func (x *AddAppointmentRegisterReq) GetDoctorId() int32 {
	if x != nil {
		return x.DoctorId
	}
	return 0
}

func (x *AddAppointmentRegisterReq) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *AddAppointmentRegisterReq) GetIdNumber() string {
	if x != nil {
		return x.IdNumber
	}
	return ""
}

func (x *AddAppointmentRegisterReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *AddAppointmentRegisterReq) GetAppointmentTime() string {
	if x != nil {
		return x.AppointmentTime
	}
	return ""
}

type CancelAppointmentRegistrationReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppointmentId int32 `protobuf:"varint,1,opt,name=appointment_id,json=appointmentId,proto3" json:"appointment_id,omitempty"`
}

func (x *CancelAppointmentRegistrationReq) Reset() {
	*x = CancelAppointmentRegistrationReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_doc_registeration_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelAppointmentRegistrationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelAppointmentRegistrationReq) ProtoMessage() {}

func (x *CancelAppointmentRegistrationReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_doc_registeration_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelAppointmentRegistrationReq.ProtoReflect.Descriptor instead.
func (*CancelAppointmentRegistrationReq) Descriptor() ([]byte, []int) {
	return file_rpc_doc_registeration_proto_rawDescGZIP(), []int{3}
}

func (x *CancelAppointmentRegistrationReq) GetAppointmentId() int32 {
	if x != nil {
		return x.AppointmentId
	}
	return 0
}

// 获取预约信息
type GetAppointmentRegistrationByIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppointmentId int32 `protobuf:"varint,1,opt,name=appointment_id,json=appointmentId,proto3" json:"appointment_id,omitempty"`
}

func (x *GetAppointmentRegistrationByIdReq) Reset() {
	*x = GetAppointmentRegistrationByIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_doc_registeration_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAppointmentRegistrationByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppointmentRegistrationByIdReq) ProtoMessage() {}

func (x *GetAppointmentRegistrationByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_doc_registeration_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppointmentRegistrationByIdReq.ProtoReflect.Descriptor instead.
func (*GetAppointmentRegistrationByIdReq) Descriptor() ([]byte, []int) {
	return file_rpc_doc_registeration_proto_rawDescGZIP(), []int{4}
}

func (x *GetAppointmentRegistrationByIdReq) GetAppointmentId() int32 {
	if x != nil {
		return x.AppointmentId
	}
	return 0
}

type GetAppointmentRegistrationByIdRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *AppointmentRegistration `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetAppointmentRegistrationByIdRes) Reset() {
	*x = GetAppointmentRegistrationByIdRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_doc_registeration_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAppointmentRegistrationByIdRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppointmentRegistrationByIdRes) ProtoMessage() {}

func (x *GetAppointmentRegistrationByIdRes) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_doc_registeration_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppointmentRegistrationByIdRes.ProtoReflect.Descriptor instead.
func (*GetAppointmentRegistrationByIdRes) Descriptor() ([]byte, []int) {
	return file_rpc_doc_registeration_proto_rawDescGZIP(), []int{5}
}

func (x *GetAppointmentRegistrationByIdRes) GetData() *AppointmentRegistration {
	if x != nil {
		return x.Data
	}
	return nil
}

// 修改预约信息
type UpdateAppointmentRegistrationReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *AppointmentRegistration `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UpdateAppointmentRegistrationReq) Reset() {
	*x = UpdateAppointmentRegistrationReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_doc_registeration_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAppointmentRegistrationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAppointmentRegistrationReq) ProtoMessage() {}

func (x *UpdateAppointmentRegistrationReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_doc_registeration_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAppointmentRegistrationReq.ProtoReflect.Descriptor instead.
func (*UpdateAppointmentRegistrationReq) Descriptor() ([]byte, []int) {
	return file_rpc_doc_registeration_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateAppointmentRegistrationReq) GetData() *AppointmentRegistration {
	if x != nil {
		return x.Data
	}
	return nil
}

type AppointmentRegistration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PatientId       int32  `protobuf:"varint,10,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	DoctorId        int32  `protobuf:"varint,20,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	RealName        string `protobuf:"bytes,30,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	IdNumber        string `protobuf:"bytes,40,opt,name=id_number,json=idNumber,proto3" json:"id_number,omitempty"`
	Mobile          string `protobuf:"bytes,50,opt,name=mobile,proto3" json:"mobile,omitempty"`
	AppointmentTime string `protobuf:"bytes,60,opt,name=appointment_time,json=appointmentTime,proto3" json:"appointment_time,omitempty"`
	Status          int32  `protobuf:"varint,70,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *AppointmentRegistration) Reset() {
	*x = AppointmentRegistration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_doc_registeration_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppointmentRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppointmentRegistration) ProtoMessage() {}

func (x *AppointmentRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_doc_registeration_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppointmentRegistration.ProtoReflect.Descriptor instead.
func (*AppointmentRegistration) Descriptor() ([]byte, []int) {
	return file_rpc_doc_registeration_proto_rawDescGZIP(), []int{7}
}

func (x *AppointmentRegistration) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AppointmentRegistration) GetPatientId() int32 {
	if x != nil {
		return x.PatientId
	}
	return 0
}

func (x *AppointmentRegistration) GetDoctorId() int32 {
	if x != nil {
		return x.DoctorId
	}
	return 0
}

func (x *AppointmentRegistration) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *AppointmentRegistration) GetIdNumber() string {
	if x != nil {
		return x.IdNumber
	}
	return ""
}

func (x *AppointmentRegistration) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *AppointmentRegistration) GetAppointmentTime() string {
	if x != nil {
		return x.AppointmentTime
	}
	return ""
}

func (x *AppointmentRegistration) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_rpc_doc_registeration_proto protoreflect.FileDescriptor

var file_rpc_doc_registeration_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x72, 0x70, 0x63, 0x2f, 0x64, 0x6f, 0x63, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x22, 0x14, 0x0a, 0x12, 0x41, 0x74, 0x74, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x50, 0x68, 0x79, 0x73, 0x69, 0x63, 0x69, 0x61, 0x6e, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x22, 0xd4, 0x01, 0x0a, 0x19, 0x41, 0x64, 0x64, 0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x14, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09,
	0x72, 0x65, 0x61, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x1e, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x72, 0x65, 0x61, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x64, 0x5f,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x28, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x64,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65,
	0x18, 0x32, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x29,
	0x0a, 0x10, 0x61, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x3c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x61, 0x70, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x49, 0x0a, 0x20, 0x43, 0x61, 0x6e,
	0x63, 0x65, 0x6c, 0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x25, 0x0a,
	0x0e, 0x61, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x61, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x22, 0x4a, 0x0a, 0x21, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x70, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0d, 0x61, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x22, 0x56, 0x0a, 0x21, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x79,
	0x49, 0x64, 0x52, 0x65, 0x73, 0x12, 0x31, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x41, 0x70, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x55, 0x0a, 0x20, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x31, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x2e, 0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0xfa, 0x01, 0x0a, 0x17, 0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70,
	0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x6f,
	0x63, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x14, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64,
	0x6f, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x61, 0x6c, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x1e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x61, 0x6c,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x64, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x28, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x32, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x61, 0x70, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x3c, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0f, 0x61, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x46,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0xf1, 0x02, 0x0a,
	0x0d, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x40,
	0x0a, 0x10, 0x41, 0x64, 0x64, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1f, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x41, 0x64, 0x64, 0x41, 0x70, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x1a, 0x0b, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x12, 0x54, 0x0a, 0x1d, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x26, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x41,
	0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x0b, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x72, 0x0a, 0x1e, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x42, 0x79, 0x49, 0x64, 0x12, 0x27, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e,
	0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65,
	0x71, 0x1a, 0x27, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x12, 0x54, 0x0a, 0x1d, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x1a, 0x0b, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_rpc_doc_registeration_proto_rawDescOnce sync.Once
	file_rpc_doc_registeration_proto_rawDescData = file_rpc_doc_registeration_proto_rawDesc
)

func file_rpc_doc_registeration_proto_rawDescGZIP() []byte {
	file_rpc_doc_registeration_proto_rawDescOnce.Do(func() {
		file_rpc_doc_registeration_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_doc_registeration_proto_rawDescData)
	})
	return file_rpc_doc_registeration_proto_rawDescData
}

var file_rpc_doc_registeration_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_rpc_doc_registeration_proto_goTypes = []interface{}{
	(*AttendingPhysician)(nil),                // 0: user.AttendingPhysician
	(*Empty)(nil),                             // 1: user.Empty
	(*AddAppointmentRegisterReq)(nil),         // 2: user.AddAppointmentRegisterReq
	(*CancelAppointmentRegistrationReq)(nil),  // 3: user.CancelAppointmentRegistrationReq
	(*GetAppointmentRegistrationByIdReq)(nil), // 4: user.GetAppointmentRegistrationByIdReq
	(*GetAppointmentRegistrationByIdRes)(nil), // 5: user.GetAppointmentRegistrationByIdRes
	(*UpdateAppointmentRegistrationReq)(nil),  // 6: user.UpdateAppointmentRegistrationReq
	(*AppointmentRegistration)(nil),           // 7: user.AppointmentRegistration
}
var file_rpc_doc_registeration_proto_depIdxs = []int32{
	7, // 0: user.GetAppointmentRegistrationByIdRes.data:type_name -> user.AppointmentRegistration
	7, // 1: user.UpdateAppointmentRegistrationReq.data:type_name -> user.AppointmentRegistration
	2, // 2: user.Registeration.AddRegisteration:input_type -> user.AddAppointmentRegisterReq
	3, // 3: user.Registeration.CancelAppointmentRegistration:input_type -> user.CancelAppointmentRegistrationReq
	4, // 4: user.Registeration.GetAppointmentRegistrationById:input_type -> user.GetAppointmentRegistrationByIdReq
	6, // 5: user.Registeration.UpdateAppointmentRegistration:input_type -> user.UpdateAppointmentRegistrationReq
	1, // 6: user.Registeration.AddRegisteration:output_type -> user.Empty
	1, // 7: user.Registeration.CancelAppointmentRegistration:output_type -> user.Empty
	5, // 8: user.Registeration.GetAppointmentRegistrationById:output_type -> user.GetAppointmentRegistrationByIdRes
	1, // 9: user.Registeration.UpdateAppointmentRegistration:output_type -> user.Empty
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_doc_registeration_proto_init() }
func file_rpc_doc_registeration_proto_init() {
	if File_rpc_doc_registeration_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_doc_registeration_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttendingPhysician); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_doc_registeration_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_doc_registeration_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddAppointmentRegisterReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_doc_registeration_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelAppointmentRegistrationReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_doc_registeration_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAppointmentRegistrationByIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_doc_registeration_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAppointmentRegistrationByIdRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_doc_registeration_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAppointmentRegistrationReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_doc_registeration_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppointmentRegistration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_doc_registeration_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_doc_registeration_proto_goTypes,
		DependencyIndexes: file_rpc_doc_registeration_proto_depIdxs,
		MessageInfos:      file_rpc_doc_registeration_proto_msgTypes,
	}.Build()
	File_rpc_doc_registeration_proto = out.File
	file_rpc_doc_registeration_proto_rawDesc = nil
	file_rpc_doc_registeration_proto_goTypes = nil
	file_rpc_doc_registeration_proto_depIdxs = nil
}
