// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: rpc/doc/registeration.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Registeration_CreateAppointment_FullMethodName                    = "/user.Registeration/CreateAppointment"
	Registeration_CancelAppointmentRegistration_FullMethodName        = "/user.Registeration/CancelAppointmentRegistration"
	Registeration_GetAppointmentById_FullMethodName                   = "/user.Registeration/GetAppointmentById"
	Registeration_GetAttendingPhysicianByAppointmentId_FullMethodName = "/user.Registeration/GetAttendingPhysicianByAppointmentId"
	Registeration_GetAttendingPhysicianByIdNumber_FullMethodName      = "/user.Registeration/GetAttendingPhysicianByIdNumber"
	Registeration_OfficeList_FullMethodName                           = "/user.Registeration/OfficeList"
	Registeration_GetOfficeDoctorListByIdTime_FullMethodName          = "/user.Registeration/GetOfficeDoctorListByIdTime"
	Registeration_DoctorDetails_FullMethodName                        = "/user.Registeration/DoctorDetails"
)

// RegisterationClient is the client API for Registeration service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RegisterationClient interface {
	// 挂号预约
	CreateAppointment(ctx context.Context, in *CreateAppointmentReq, opts ...grpc.CallOption) (*Empty, error)
	// 取消预约
	CancelAppointmentRegistration(ctx context.Context, in *CancelAppointmentRegistrationReq, opts ...grpc.CallOption) (*Empty, error)
	// 获取预约信息
	GetAppointmentById(ctx context.Context, in *GetAppointmentByIdReq, opts ...grpc.CallOption) (*GetAppointmentByIdRes, error)
	// 获取挂号信息  根据预约id
	GetAttendingPhysicianByAppointmentId(ctx context.Context, in *GetAttendingPhysicianByAppointmentIdReq, opts ...grpc.CallOption) (*GetAttendingPhysicianByAppointmentIdRes, error)
	// 获取挂号信息 根据身份证号
	GetAttendingPhysicianByIdNumber(ctx context.Context, in *GetAttendingPhysicianByIdNumberReq, opts ...grpc.CallOption) (*GetAttendingPhysicianByIdNumberRes, error)
	// ------------------------------------------------//todo 医生模块--------------------------------------------------------
	// 科室列表
	OfficeList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*OfficeListRes, error)
	// 排班科室医生列表
	GetOfficeDoctorListByIdTime(ctx context.Context, in *OfficeDoctorListByIdTimeReq, opts ...grpc.CallOption) (*OfficeDoctorListByIdTimeRes, error)
	// 医生详情
	DoctorDetails(ctx context.Context, in *DoctorDetailsReq, opts ...grpc.CallOption) (*DoctorDetailsRes, error)
}

type registerationClient struct {
	cc grpc.ClientConnInterface
}

func NewRegisterationClient(cc grpc.ClientConnInterface) RegisterationClient {
	return &registerationClient{cc}
}

func (c *registerationClient) CreateAppointment(ctx context.Context, in *CreateAppointmentReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, Registeration_CreateAppointment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registerationClient) CancelAppointmentRegistration(ctx context.Context, in *CancelAppointmentRegistrationReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, Registeration_CancelAppointmentRegistration_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registerationClient) GetAppointmentById(ctx context.Context, in *GetAppointmentByIdReq, opts ...grpc.CallOption) (*GetAppointmentByIdRes, error) {
	out := new(GetAppointmentByIdRes)
	err := c.cc.Invoke(ctx, Registeration_GetAppointmentById_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registerationClient) GetAttendingPhysicianByAppointmentId(ctx context.Context, in *GetAttendingPhysicianByAppointmentIdReq, opts ...grpc.CallOption) (*GetAttendingPhysicianByAppointmentIdRes, error) {
	out := new(GetAttendingPhysicianByAppointmentIdRes)
	err := c.cc.Invoke(ctx, Registeration_GetAttendingPhysicianByAppointmentId_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registerationClient) GetAttendingPhysicianByIdNumber(ctx context.Context, in *GetAttendingPhysicianByIdNumberReq, opts ...grpc.CallOption) (*GetAttendingPhysicianByIdNumberRes, error) {
	out := new(GetAttendingPhysicianByIdNumberRes)
	err := c.cc.Invoke(ctx, Registeration_GetAttendingPhysicianByIdNumber_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registerationClient) OfficeList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*OfficeListRes, error) {
	out := new(OfficeListRes)
	err := c.cc.Invoke(ctx, Registeration_OfficeList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registerationClient) GetOfficeDoctorListByIdTime(ctx context.Context, in *OfficeDoctorListByIdTimeReq, opts ...grpc.CallOption) (*OfficeDoctorListByIdTimeRes, error) {
	out := new(OfficeDoctorListByIdTimeRes)
	err := c.cc.Invoke(ctx, Registeration_GetOfficeDoctorListByIdTime_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registerationClient) DoctorDetails(ctx context.Context, in *DoctorDetailsReq, opts ...grpc.CallOption) (*DoctorDetailsRes, error) {
	out := new(DoctorDetailsRes)
	err := c.cc.Invoke(ctx, Registeration_DoctorDetails_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegisterationServer is the server API for Registeration service.
// All implementations must embed UnimplementedRegisterationServer
// for forward compatibility
type RegisterationServer interface {
	// 挂号预约
	CreateAppointment(context.Context, *CreateAppointmentReq) (*Empty, error)
	// 取消预约
	CancelAppointmentRegistration(context.Context, *CancelAppointmentRegistrationReq) (*Empty, error)
	// 获取预约信息
	GetAppointmentById(context.Context, *GetAppointmentByIdReq) (*GetAppointmentByIdRes, error)
	// 获取挂号信息  根据预约id
	GetAttendingPhysicianByAppointmentId(context.Context, *GetAttendingPhysicianByAppointmentIdReq) (*GetAttendingPhysicianByAppointmentIdRes, error)
	// 获取挂号信息 根据身份证号
	GetAttendingPhysicianByIdNumber(context.Context, *GetAttendingPhysicianByIdNumberReq) (*GetAttendingPhysicianByIdNumberRes, error)
	// ------------------------------------------------//todo 医生模块--------------------------------------------------------
	// 科室列表
	OfficeList(context.Context, *Empty) (*OfficeListRes, error)
	// 排班科室医生列表
	GetOfficeDoctorListByIdTime(context.Context, *OfficeDoctorListByIdTimeReq) (*OfficeDoctorListByIdTimeRes, error)
	// 医生详情
	DoctorDetails(context.Context, *DoctorDetailsReq) (*DoctorDetailsRes, error)
	mustEmbedUnimplementedRegisterationServer()
}

// UnimplementedRegisterationServer must be embedded to have forward compatible implementations.
type UnimplementedRegisterationServer struct {
}

func (UnimplementedRegisterationServer) CreateAppointment(context.Context, *CreateAppointmentReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAppointment not implemented")
}
func (UnimplementedRegisterationServer) CancelAppointmentRegistration(context.Context, *CancelAppointmentRegistrationReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelAppointmentRegistration not implemented")
}
func (UnimplementedRegisterationServer) GetAppointmentById(context.Context, *GetAppointmentByIdReq) (*GetAppointmentByIdRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAppointmentById not implemented")
}
func (UnimplementedRegisterationServer) GetAttendingPhysicianByAppointmentId(context.Context, *GetAttendingPhysicianByAppointmentIdReq) (*GetAttendingPhysicianByAppointmentIdRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAttendingPhysicianByAppointmentId not implemented")
}
func (UnimplementedRegisterationServer) GetAttendingPhysicianByIdNumber(context.Context, *GetAttendingPhysicianByIdNumberReq) (*GetAttendingPhysicianByIdNumberRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAttendingPhysicianByIdNumber not implemented")
}
func (UnimplementedRegisterationServer) OfficeList(context.Context, *Empty) (*OfficeListRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OfficeList not implemented")
}
func (UnimplementedRegisterationServer) GetOfficeDoctorListByIdTime(context.Context, *OfficeDoctorListByIdTimeReq) (*OfficeDoctorListByIdTimeRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOfficeDoctorListByIdTime not implemented")
}
func (UnimplementedRegisterationServer) DoctorDetails(context.Context, *DoctorDetailsReq) (*DoctorDetailsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoctorDetails not implemented")
}
func (UnimplementedRegisterationServer) mustEmbedUnimplementedRegisterationServer() {}

// UnsafeRegisterationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegisterationServer will
// result in compilation errors.
type UnsafeRegisterationServer interface {
	mustEmbedUnimplementedRegisterationServer()
}

func RegisterRegisterationServer(s grpc.ServiceRegistrar, srv RegisterationServer) {
	s.RegisterService(&Registeration_ServiceDesc, srv)
}

func _Registeration_CreateAppointment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAppointmentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegisterationServer).CreateAppointment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registeration_CreateAppointment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegisterationServer).CreateAppointment(ctx, req.(*CreateAppointmentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registeration_CancelAppointmentRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelAppointmentRegistrationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegisterationServer).CancelAppointmentRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registeration_CancelAppointmentRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegisterationServer).CancelAppointmentRegistration(ctx, req.(*CancelAppointmentRegistrationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registeration_GetAppointmentById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppointmentByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegisterationServer).GetAppointmentById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registeration_GetAppointmentById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegisterationServer).GetAppointmentById(ctx, req.(*GetAppointmentByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registeration_GetAttendingPhysicianByAppointmentId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttendingPhysicianByAppointmentIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegisterationServer).GetAttendingPhysicianByAppointmentId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registeration_GetAttendingPhysicianByAppointmentId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegisterationServer).GetAttendingPhysicianByAppointmentId(ctx, req.(*GetAttendingPhysicianByAppointmentIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registeration_GetAttendingPhysicianByIdNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttendingPhysicianByIdNumberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegisterationServer).GetAttendingPhysicianByIdNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registeration_GetAttendingPhysicianByIdNumber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegisterationServer).GetAttendingPhysicianByIdNumber(ctx, req.(*GetAttendingPhysicianByIdNumberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registeration_OfficeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegisterationServer).OfficeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registeration_OfficeList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegisterationServer).OfficeList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registeration_GetOfficeDoctorListByIdTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OfficeDoctorListByIdTimeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegisterationServer).GetOfficeDoctorListByIdTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registeration_GetOfficeDoctorListByIdTime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegisterationServer).GetOfficeDoctorListByIdTime(ctx, req.(*OfficeDoctorListByIdTimeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registeration_DoctorDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoctorDetailsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegisterationServer).DoctorDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registeration_DoctorDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegisterationServer).DoctorDetails(ctx, req.(*DoctorDetailsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Registeration_ServiceDesc is the grpc.ServiceDesc for Registeration service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Registeration_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.Registeration",
	HandlerType: (*RegisterationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAppointment",
			Handler:    _Registeration_CreateAppointment_Handler,
		},
		{
			MethodName: "CancelAppointmentRegistration",
			Handler:    _Registeration_CancelAppointmentRegistration_Handler,
		},
		{
			MethodName: "GetAppointmentById",
			Handler:    _Registeration_GetAppointmentById_Handler,
		},
		{
			MethodName: "GetAttendingPhysicianByAppointmentId",
			Handler:    _Registeration_GetAttendingPhysicianByAppointmentId_Handler,
		},
		{
			MethodName: "GetAttendingPhysicianByIdNumber",
			Handler:    _Registeration_GetAttendingPhysicianByIdNumber_Handler,
		},
		{
			MethodName: "OfficeList",
			Handler:    _Registeration_OfficeList_Handler,
		},
		{
			MethodName: "GetOfficeDoctorListByIdTime",
			Handler:    _Registeration_GetOfficeDoctorListByIdTime_Handler,
		},
		{
			MethodName: "DoctorDetails",
			Handler:    _Registeration_DoctorDetails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/doc/registeration.proto",
}
