// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.4
// source: rpc/doc/registeration.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 预约  增删改查
type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_doc_registeration_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_doc_registeration_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_rpc_doc_registeration_proto_rawDescGZIP(), []int{0}
}

// 预约
type CreateAppointmentReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId          int32  `protobuf:"varint,10,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OfficeId        int32  `protobuf:"varint,20,opt,name=office_id,json=officeId,proto3" json:"office_id,omitempty"`
	AppointmentType int32  `protobuf:"varint,30,opt,name=appointment_type,json=appointmentType,proto3" json:"appointment_type,omitempty"`
	AppointmentData string `protobuf:"bytes,50,opt,name=appointment_data,json=appointmentData,proto3" json:"appointment_data,omitempty"`
	Status          int32  `protobuf:"varint,70,opt,name=status,proto3" json:"status,omitempty"`
	DoctorId        int32  `protobuf:"varint,40,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	RealName        string `protobuf:"bytes,60,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	IdNumber        string `protobuf:"bytes,80,opt,name=id_number,json=idNumber,proto3" json:"id_number,omitempty"`
	Mobile          string `protobuf:"bytes,81,opt,name=mobile,proto3" json:"mobile,omitempty"`
	ShiftId         int32  `protobuf:"varint,90,opt,name=shift_id,json=shiftId,proto3" json:"shift_id,omitempty"`
}

func (x *CreateAppointmentReq) Reset() {
	*x = CreateAppointmentReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_doc_registeration_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAppointmentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAppointmentReq) ProtoMessage() {}

func (x *CreateAppointmentReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_doc_registeration_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAppointmentReq.ProtoReflect.Descriptor instead.
func (*CreateAppointmentReq) Descriptor() ([]byte, []int) {
	return file_rpc_doc_registeration_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAppointmentReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateAppointmentReq) GetOfficeId() int32 {
	if x != nil {
		return x.OfficeId
	}
	return 0
}

func (x *CreateAppointmentReq) GetAppointmentType() int32 {
	if x != nil {
		return x.AppointmentType
	}
	return 0
}

func (x *CreateAppointmentReq) GetAppointmentData() string {
	if x != nil {
		return x.AppointmentData
	}
	return ""
}

func (x *CreateAppointmentReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateAppointmentReq) GetDoctorId() int32 {
	if x != nil {
		return x.DoctorId
	}
	return 0
}

func (x *CreateAppointmentReq) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *CreateAppointmentReq) GetIdNumber() string {
	if x != nil {
		return x.IdNumber
	}
	return ""
}

func (x *CreateAppointmentReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *CreateAppointmentReq) GetShiftId() int32 {
	if x != nil {
		return x.ShiftId
	}
	return 0
}

// 取消预约
type CancelAppointmentRegistrationReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppointmentId int32 `protobuf:"varint,10,opt,name=appointment_id,json=appointmentId,proto3" json:"appointment_id,omitempty"`
	ShiftId       int32 `protobuf:"varint,20,opt,name=shift_id,json=shiftId,proto3" json:"shift_id,omitempty"`
}

func (x *CancelAppointmentRegistrationReq) Reset() {
	*x = CancelAppointmentRegistrationReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_doc_registeration_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelAppointmentRegistrationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelAppointmentRegistrationReq) ProtoMessage() {}

func (x *CancelAppointmentRegistrationReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_doc_registeration_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelAppointmentRegistrationReq.ProtoReflect.Descriptor instead.
func (*CancelAppointmentRegistrationReq) Descriptor() ([]byte, []int) {
	return file_rpc_doc_registeration_proto_rawDescGZIP(), []int{2}
}

func (x *CancelAppointmentRegistrationReq) GetAppointmentId() int32 {
	if x != nil {
		return x.AppointmentId
	}
	return 0
}

func (x *CancelAppointmentRegistrationReq) GetShiftId() int32 {
	if x != nil {
		return x.ShiftId
	}
	return 0
}

// 获取预约信息
type GetAppointmentByIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppointmentId int32  `protobuf:"varint,1,opt,name=appointment_id,json=appointmentId,proto3" json:"appointment_id,omitempty"`
	IdNumber      string `protobuf:"bytes,2,opt,name=id_number,json=idNumber,proto3" json:"id_number,omitempty"`
}

func (x *GetAppointmentByIdReq) Reset() {
	*x = GetAppointmentByIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_doc_registeration_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAppointmentByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppointmentByIdReq) ProtoMessage() {}

func (x *GetAppointmentByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_doc_registeration_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppointmentByIdReq.ProtoReflect.Descriptor instead.
func (*GetAppointmentByIdReq) Descriptor() ([]byte, []int) {
	return file_rpc_doc_registeration_proto_rawDescGZIP(), []int{3}
}

func (x *GetAppointmentByIdReq) GetAppointmentId() int32 {
	if x != nil {
		return x.AppointmentId
	}
	return 0
}

func (x *GetAppointmentByIdReq) GetIdNumber() string {
	if x != nil {
		return x.IdNumber
	}
	return ""
}

type GetAppointmentByIdRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Appointment `protobuf:"bytes,10,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetAppointmentByIdRes) Reset() {
	*x = GetAppointmentByIdRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_doc_registeration_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAppointmentByIdRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppointmentByIdRes) ProtoMessage() {}

func (x *GetAppointmentByIdRes) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_doc_registeration_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppointmentByIdRes.ProtoReflect.Descriptor instead.
func (*GetAppointmentByIdRes) Descriptor() ([]byte, []int) {
	return file_rpc_doc_registeration_proto_rawDescGZIP(), []int{4}
}

func (x *GetAppointmentByIdRes) GetData() *Appointment {
	if x != nil {
		return x.Data
	}
	return nil
}

// 获取挂号信息
type GetAttendingPhysicianByAppointmentIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppointmentId int32 `protobuf:"varint,1,opt,name=appointment_id,json=appointmentId,proto3" json:"appointment_id,omitempty"`
}

func (x *GetAttendingPhysicianByAppointmentIdReq) Reset() {
	*x = GetAttendingPhysicianByAppointmentIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_doc_registeration_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAttendingPhysicianByAppointmentIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttendingPhysicianByAppointmentIdReq) ProtoMessage() {}

func (x *GetAttendingPhysicianByAppointmentIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_doc_registeration_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttendingPhysicianByAppointmentIdReq.ProtoReflect.Descriptor instead.
func (*GetAttendingPhysicianByAppointmentIdReq) Descriptor() ([]byte, []int) {
	return file_rpc_doc_registeration_proto_rawDescGZIP(), []int{5}
}

func (x *GetAttendingPhysicianByAppointmentIdReq) GetAppointmentId() int32 {
	if x != nil {
		return x.AppointmentId
	}
	return 0
}

type GetAttendingPhysicianByAppointmentIdRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *AttendingPhysician `protobuf:"bytes,10,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetAttendingPhysicianByAppointmentIdRes) Reset() {
	*x = GetAttendingPhysicianByAppointmentIdRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_doc_registeration_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAttendingPhysicianByAppointmentIdRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttendingPhysicianByAppointmentIdRes) ProtoMessage() {}

func (x *GetAttendingPhysicianByAppointmentIdRes) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_doc_registeration_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttendingPhysicianByAppointmentIdRes.ProtoReflect.Descriptor instead.
func (*GetAttendingPhysicianByAppointmentIdRes) Descriptor() ([]byte, []int) {
	return file_rpc_doc_registeration_proto_rawDescGZIP(), []int{6}
}

func (x *GetAttendingPhysicianByAppointmentIdRes) GetData() *AttendingPhysician {
	if x != nil {
		return x.Data
	}
	return nil
}

// 获取挂号信息 (根据身份证号）
type GetAttendingPhysicianByIdNumberReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdNumber string `protobuf:"bytes,1,opt,name=id_number,json=idNumber,proto3" json:"id_number,omitempty"`
}

func (x *GetAttendingPhysicianByIdNumberReq) Reset() {
	*x = GetAttendingPhysicianByIdNumberReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_doc_registeration_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAttendingPhysicianByIdNumberReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttendingPhysicianByIdNumberReq) ProtoMessage() {}

func (x *GetAttendingPhysicianByIdNumberReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_doc_registeration_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttendingPhysicianByIdNumberReq.ProtoReflect.Descriptor instead.
func (*GetAttendingPhysicianByIdNumberReq) Descriptor() ([]byte, []int) {
	return file_rpc_doc_registeration_proto_rawDescGZIP(), []int{7}
}

func (x *GetAttendingPhysicianByIdNumberReq) GetIdNumber() string {
	if x != nil {
		return x.IdNumber
	}
	return ""
}

type GetAttendingPhysicianByIdNumberRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*AttendingPhysician `protobuf:"bytes,10,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetAttendingPhysicianByIdNumberRes) Reset() {
	*x = GetAttendingPhysicianByIdNumberRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_doc_registeration_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAttendingPhysicianByIdNumberRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttendingPhysicianByIdNumberRes) ProtoMessage() {}

func (x *GetAttendingPhysicianByIdNumberRes) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_doc_registeration_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttendingPhysicianByIdNumberRes.ProtoReflect.Descriptor instead.
func (*GetAttendingPhysicianByIdNumberRes) Descriptor() ([]byte, []int) {
	return file_rpc_doc_registeration_proto_rawDescGZIP(), []int{8}
}

func (x *GetAttendingPhysicianByIdNumberRes) GetData() []*AttendingPhysician {
	if x != nil {
		return x.Data
	}
	return nil
}

// ------------------------------------------------//todo 医生模块--------------------------------------------------------
// 科室列表
type OfficeListRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*DoctorOffice `protobuf:"bytes,10,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *OfficeListRes) Reset() {
	*x = OfficeListRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_doc_registeration_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OfficeListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfficeListRes) ProtoMessage() {}

func (x *OfficeListRes) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_doc_registeration_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfficeListRes.ProtoReflect.Descriptor instead.
func (*OfficeListRes) Descriptor() ([]byte, []int) {
	return file_rpc_doc_registeration_proto_rawDescGZIP(), []int{9}
}

func (x *OfficeListRes) GetData() []*DoctorOffice {
	if x != nil {
		return x.Data
	}
	return nil
}

// 排班科室医生列表
type OfficeDoctorListByIdTimeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OfficeId  int32  `protobuf:"varint,10,opt,name=office_id,json=officeId,proto3" json:"office_id,omitempty"`
	ShiftTime string `protobuf:"bytes,20,opt,name=shift_time,json=shiftTime,proto3" json:"shift_time,omitempty"`
}

func (x *OfficeDoctorListByIdTimeReq) Reset() {
	*x = OfficeDoctorListByIdTimeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_doc_registeration_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OfficeDoctorListByIdTimeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfficeDoctorListByIdTimeReq) ProtoMessage() {}

func (x *OfficeDoctorListByIdTimeReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_doc_registeration_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfficeDoctorListByIdTimeReq.ProtoReflect.Descriptor instead.
func (*OfficeDoctorListByIdTimeReq) Descriptor() ([]byte, []int) {
	return file_rpc_doc_registeration_proto_rawDescGZIP(), []int{10}
}

func (x *OfficeDoctorListByIdTimeReq) GetOfficeId() int32 {
	if x != nil {
		return x.OfficeId
	}
	return 0
}

func (x *OfficeDoctorListByIdTimeReq) GetShiftTime() string {
	if x != nil {
		return x.ShiftTime
	}
	return ""
}

type OfficeDoctorListByIdTimeRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*ShiftDoctor `protobuf:"bytes,10,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *OfficeDoctorListByIdTimeRes) Reset() {
	*x = OfficeDoctorListByIdTimeRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_doc_registeration_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OfficeDoctorListByIdTimeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfficeDoctorListByIdTimeRes) ProtoMessage() {}

func (x *OfficeDoctorListByIdTimeRes) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_doc_registeration_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfficeDoctorListByIdTimeRes.ProtoReflect.Descriptor instead.
func (*OfficeDoctorListByIdTimeRes) Descriptor() ([]byte, []int) {
	return file_rpc_doc_registeration_proto_rawDescGZIP(), []int{11}
}

func (x *OfficeDoctorListByIdTimeRes) GetData() []*ShiftDoctor {
	if x != nil {
		return x.Data
	}
	return nil
}

// 医生详情
type DoctorDetailsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DoctorId int32 `protobuf:"varint,10,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
}

func (x *DoctorDetailsReq) Reset() {
	*x = DoctorDetailsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_doc_registeration_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoctorDetailsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorDetailsReq) ProtoMessage() {}

func (x *DoctorDetailsReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_doc_registeration_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorDetailsReq.ProtoReflect.Descriptor instead.
func (*DoctorDetailsReq) Descriptor() ([]byte, []int) {
	return file_rpc_doc_registeration_proto_rawDescGZIP(), []int{12}
}

func (x *DoctorDetailsReq) GetDoctorId() int32 {
	if x != nil {
		return x.DoctorId
	}
	return 0
}

type DoctorDetailsRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Doctor `protobuf:"bytes,10,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *DoctorDetailsRes) Reset() {
	*x = DoctorDetailsRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_doc_registeration_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoctorDetailsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorDetailsRes) ProtoMessage() {}

func (x *DoctorDetailsRes) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_doc_registeration_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorDetailsRes.ProtoReflect.Descriptor instead.
func (*DoctorDetailsRes) Descriptor() ([]byte, []int) {
	return file_rpc_doc_registeration_proto_rawDescGZIP(), []int{13}
}

func (x *DoctorDetailsRes) GetData() *Doctor {
	if x != nil {
		return x.Data
	}
	return nil
}

// 用户预约
type Appointment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              int32  `protobuf:"varint,10,opt,name=id,proto3" json:"id,omitempty"`
	UserId          int32  `protobuf:"varint,20,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AppointmentType int32  `protobuf:"varint,30,opt,name=appointment_type,json=appointmentType,proto3" json:"appointment_type,omitempty"`
	AppointmentData string `protobuf:"bytes,50,opt,name=appointment_data,json=appointmentData,proto3" json:"appointment_data,omitempty"`
	AppointmentTime string `protobuf:"bytes,60,opt,name=appointment_time,json=appointmentTime,proto3" json:"appointment_time,omitempty"`
	Status          int32  `protobuf:"varint,70,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *Appointment) Reset() {
	*x = Appointment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_doc_registeration_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Appointment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Appointment) ProtoMessage() {}

func (x *Appointment) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_doc_registeration_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Appointment.ProtoReflect.Descriptor instead.
func (*Appointment) Descriptor() ([]byte, []int) {
	return file_rpc_doc_registeration_proto_rawDescGZIP(), []int{14}
}

func (x *Appointment) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Appointment) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Appointment) GetAppointmentType() int32 {
	if x != nil {
		return x.AppointmentType
	}
	return 0
}

func (x *Appointment) GetAppointmentData() string {
	if x != nil {
		return x.AppointmentData
	}
	return ""
}

func (x *Appointment) GetAppointmentTime() string {
	if x != nil {
		return x.AppointmentTime
	}
	return ""
}

func (x *Appointment) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 用户挂号
type AttendingPhysician struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int32  `protobuf:"varint,10,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32  `protobuf:"varint,20,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AppointmentId int32  `protobuf:"varint,30,opt,name=appointment_id,json=appointmentId,proto3" json:"appointment_id,omitempty"`
	DoctorID      int32  `protobuf:"varint,40,opt,name=DoctorID,proto3" json:"DoctorID,omitempty"`
	OfficeID      int32  `protobuf:"varint,50,opt,name=OfficeID,proto3" json:"OfficeID,omitempty"`
	RealName      string `protobuf:"bytes,60,opt,name=RealName,proto3" json:"RealName,omitempty"`
	IDNumber      string `protobuf:"bytes,80,opt,name=IDNumber,proto3" json:"IDNumber,omitempty"`
	Mobile        string `protobuf:"bytes,81,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Symptoms      string `protobuf:"bytes,90,opt,name=Symptoms,proto3" json:"Symptoms,omitempty"`
	Diagnosis     string `protobuf:"bytes,100,opt,name=Diagnosis,proto3" json:"Diagnosis,omitempty"`
	Prescription  string `protobuf:"bytes,110,opt,name=Prescription,proto3" json:"Prescription,omitempty"`
	ShiftId       int32  `protobuf:"varint,120,opt,name=ShiftId,proto3" json:"ShiftId,omitempty"`
}

func (x *AttendingPhysician) Reset() {
	*x = AttendingPhysician{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_doc_registeration_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttendingPhysician) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttendingPhysician) ProtoMessage() {}

func (x *AttendingPhysician) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_doc_registeration_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttendingPhysician.ProtoReflect.Descriptor instead.
func (*AttendingPhysician) Descriptor() ([]byte, []int) {
	return file_rpc_doc_registeration_proto_rawDescGZIP(), []int{15}
}

func (x *AttendingPhysician) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AttendingPhysician) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AttendingPhysician) GetAppointmentId() int32 {
	if x != nil {
		return x.AppointmentId
	}
	return 0
}

func (x *AttendingPhysician) GetDoctorID() int32 {
	if x != nil {
		return x.DoctorID
	}
	return 0
}

func (x *AttendingPhysician) GetOfficeID() int32 {
	if x != nil {
		return x.OfficeID
	}
	return 0
}

func (x *AttendingPhysician) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *AttendingPhysician) GetIDNumber() string {
	if x != nil {
		return x.IDNumber
	}
	return ""
}

func (x *AttendingPhysician) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *AttendingPhysician) GetSymptoms() string {
	if x != nil {
		return x.Symptoms
	}
	return ""
}

func (x *AttendingPhysician) GetDiagnosis() string {
	if x != nil {
		return x.Diagnosis
	}
	return ""
}

func (x *AttendingPhysician) GetPrescription() string {
	if x != nil {
		return x.Prescription
	}
	return ""
}

func (x *AttendingPhysician) GetShiftId() int32 {
	if x != nil {
		return x.ShiftId
	}
	return 0
}

// 科室
type DoctorOffice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int32     `protobuf:"varint,10,opt,name=id,proto3" json:"id,omitempty"`
	OfficeName string    `protobuf:"bytes,20,opt,name=office_name,json=officeName,proto3" json:"office_name,omitempty"`
	Status     int32     `protobuf:"varint,30,opt,name=status,proto3" json:"status,omitempty"`
	Pid        int32     `protobuf:"varint,40,opt,name=pid,proto3" json:"pid,omitempty"`
	Doctor     []*Doctor `protobuf:"bytes,50,rep,name=Doctor,proto3" json:"Doctor,omitempty"`
}

func (x *DoctorOffice) Reset() {
	*x = DoctorOffice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_doc_registeration_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoctorOffice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorOffice) ProtoMessage() {}

func (x *DoctorOffice) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_doc_registeration_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorOffice.ProtoReflect.Descriptor instead.
func (*DoctorOffice) Descriptor() ([]byte, []int) {
	return file_rpc_doc_registeration_proto_rawDescGZIP(), []int{16}
}

func (x *DoctorOffice) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DoctorOffice) GetOfficeName() string {
	if x != nil {
		return x.OfficeName
	}
	return ""
}

func (x *DoctorOffice) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DoctorOffice) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *DoctorOffice) GetDoctor() []*Doctor {
	if x != nil {
		return x.Doctor
	}
	return nil
}

// 医生
type Doctor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int32  `protobuf:"varint,10,opt,name=id,proto3" json:"id,omitempty"`
	DoctorName  string `protobuf:"bytes,20,opt,name=doctor_name,json=doctorName,proto3" json:"doctor_name,omitempty"`
	Age         int32  `protobuf:"varint,30,opt,name=age,proto3" json:"age,omitempty"`
	Sex         int32  `protobuf:"varint,40,opt,name=sex,proto3" json:"sex,omitempty"`
	Position    string `protobuf:"bytes,50,opt,name=position,proto3" json:"position,omitempty"`
	Tag         string `protobuf:"bytes,60,opt,name=tag,proto3" json:"tag,omitempty"`
	Description string `protobuf:"bytes,70,opt,name=description,proto3" json:"description,omitempty"`
	WorkAge     int32  `protobuf:"varint,80,opt,name=work_age,json=workAge,proto3" json:"work_age,omitempty"`
	WorkTime    string `protobuf:"bytes,90,opt,name=work_time,json=workTime,proto3" json:"work_time,omitempty"`
	OfficeId    int32  `protobuf:"varint,100,opt,name=office_id,json=officeId,proto3" json:"office_id,omitempty"`
	Status      int32  `protobuf:"varint,110,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *Doctor) Reset() {
	*x = Doctor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_doc_registeration_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Doctor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Doctor) ProtoMessage() {}

func (x *Doctor) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_doc_registeration_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Doctor.ProtoReflect.Descriptor instead.
func (*Doctor) Descriptor() ([]byte, []int) {
	return file_rpc_doc_registeration_proto_rawDescGZIP(), []int{17}
}

func (x *Doctor) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Doctor) GetDoctorName() string {
	if x != nil {
		return x.DoctorName
	}
	return ""
}

func (x *Doctor) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Doctor) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *Doctor) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *Doctor) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Doctor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Doctor) GetWorkAge() int32 {
	if x != nil {
		return x.WorkAge
	}
	return 0
}

func (x *Doctor) GetWorkTime() string {
	if x != nil {
		return x.WorkTime
	}
	return ""
}

func (x *Doctor) GetOfficeId() int32 {
	if x != nil {
		return x.OfficeId
	}
	return 0
}

func (x *Doctor) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 排班医生
type ShiftDoctor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32  `protobuf:"varint,10,opt,name=id,proto3" json:"id,omitempty"`
	OfficeId int32  `protobuf:"varint,20,opt,name=office_id,json=officeId,proto3" json:"office_id,omitempty"`
	DoctorId int32  `protobuf:"varint,30,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	Data     string `protobuf:"bytes,40,opt,name=data,proto3" json:"data,omitempty"`
	Time     int32  `protobuf:"varint,50,opt,name=time,proto3" json:"time,omitempty"`
	Count    int32  `protobuf:"varint,60,opt,name=count,proto3" json:"count,omitempty"`
	Status   int32  `protobuf:"varint,70,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *ShiftDoctor) Reset() {
	*x = ShiftDoctor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_doc_registeration_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShiftDoctor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShiftDoctor) ProtoMessage() {}

func (x *ShiftDoctor) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_doc_registeration_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShiftDoctor.ProtoReflect.Descriptor instead.
func (*ShiftDoctor) Descriptor() ([]byte, []int) {
	return file_rpc_doc_registeration_proto_rawDescGZIP(), []int{18}
}

func (x *ShiftDoctor) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ShiftDoctor) GetOfficeId() int32 {
	if x != nil {
		return x.OfficeId
	}
	return 0
}

func (x *ShiftDoctor) GetDoctorId() int32 {
	if x != nil {
		return x.DoctorId
	}
	return 0
}

func (x *ShiftDoctor) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *ShiftDoctor) GetTime() int32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *ShiftDoctor) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ShiftDoctor) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_rpc_doc_registeration_proto protoreflect.FileDescriptor

var file_rpc_doc_registeration_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x72, 0x70, 0x63, 0x2f, 0x64, 0x6f, 0x63, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0xc4, 0x02, 0x0a,
	0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x6f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x14, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x6f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x10, 0x61,
	0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x1e, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x61, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65,
	0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x61, 0x70, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x32, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0f, 0x61, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x46, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x6f, 0x63,
	0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x28, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x6f,
	0x63, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x61, 0x6c, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x3c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x61, 0x6c, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x64, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x50, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x51, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x68, 0x69, 0x66,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x5a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x73, 0x68, 0x69, 0x66,
	0x74, 0x49, 0x64, 0x22, 0x64, 0x0a, 0x20, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x41, 0x70, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x70, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0d, 0x61, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x19,
	0x0a, 0x08, 0x73, 0x68, 0x69, 0x66, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x14, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x73, 0x68, 0x69, 0x66, 0x74, 0x49, 0x64, 0x22, 0x5b, 0x0a, 0x15, 0x47, 0x65, 0x74,
	0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52,
	0x65, 0x71, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x61, 0x70, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x64, 0x5f,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x64,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x3e, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x12,
	0x25, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x2e, 0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x50, 0x0a, 0x27, 0x47, 0x65, 0x74, 0x41, 0x74, 0x74,
	0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x68, 0x79, 0x73, 0x69, 0x63, 0x69, 0x61, 0x6e, 0x42,
	0x79, 0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x52, 0x65,
	0x71, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x61, 0x70, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x57, 0x0a, 0x27, 0x47, 0x65, 0x74, 0x41,
	0x74, 0x74, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x68, 0x79, 0x73, 0x69, 0x63, 0x69, 0x61,
	0x6e, 0x42, 0x79, 0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x52, 0x65, 0x73, 0x12, 0x2c, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x41, 0x74, 0x74, 0x65, 0x6e, 0x64, 0x69,
	0x6e, 0x67, 0x50, 0x68, 0x79, 0x73, 0x69, 0x63, 0x69, 0x61, 0x6e, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x41, 0x0a, 0x22, 0x47, 0x65, 0x74, 0x41, 0x74, 0x74, 0x65, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x50, 0x68, 0x79, 0x73, 0x69, 0x63, 0x69, 0x61, 0x6e, 0x42, 0x79, 0x49, 0x64, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x64, 0x5f, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x64, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x22, 0x52, 0x0a, 0x22, 0x47, 0x65, 0x74, 0x41, 0x74, 0x74, 0x65, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x50, 0x68, 0x79, 0x73, 0x69, 0x63, 0x69, 0x61, 0x6e, 0x42, 0x79, 0x49,
	0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x2c, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e,
	0x41, 0x74, 0x74, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x68, 0x79, 0x73, 0x69, 0x63, 0x69,
	0x61, 0x6e, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x37, 0x0a, 0x0d, 0x4f, 0x66, 0x66, 0x69,
	0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x44,
	0x6f, 0x63, 0x74, 0x6f, 0x72, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x59, 0x0a, 0x1b, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x44, 0x6f, 0x63, 0x74, 0x6f,
	0x72, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x49, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x1b, 0x0a, 0x09, 0x6f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x6f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x73, 0x68, 0x69, 0x66, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x14, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x73, 0x68, 0x69, 0x66, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x44, 0x0a, 0x1b,
	0x4f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x4c, 0x69, 0x73, 0x74,
	0x42, 0x79, 0x49, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x53, 0x68, 0x69, 0x66, 0x74, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x2f, 0x0a, 0x10, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x6f, 0x63, 0x74, 0x6f,
	0x72, 0x49, 0x64, 0x22, 0x34, 0x0a, 0x10, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x12, 0x20, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x44, 0x6f, 0x63,
	0x74, 0x6f, 0x72, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xcf, 0x01, 0x0a, 0x0b, 0x41, 0x70,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x14, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x29, 0x0a, 0x10, 0x61, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e,
	0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x1e, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x61, 0x70,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x29, 0x0a,
	0x10, 0x61, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x32, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x61, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x6d, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x29, 0x0a, 0x10, 0x61, 0x70, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x3c, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0f, 0x61, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x46, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xe4, 0x02, 0x0a, 0x12,
	0x41, 0x74, 0x74, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x68, 0x79, 0x73, 0x69, 0x63, 0x69,
	0x61, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x14, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x61,
	0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x1e, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0d, 0x61, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x44, 0x18, 0x28,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x44, 0x12, 0x1a,
	0x0a, 0x08, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x49, 0x44, 0x18, 0x32, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65,
	0x61, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x3c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x52, 0x65,
	0x61, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x49, 0x44, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x50, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x49, 0x44, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x51, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x79,
	0x6d, 0x70, 0x74, 0x6f, 0x6d, 0x73, 0x18, 0x5a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x53, 0x79,
	0x6d, 0x70, 0x74, 0x6f, 0x6d, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f,
	0x73, 0x69, 0x73, 0x18, 0x64, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x44, 0x69, 0x61, 0x67, 0x6e,
	0x6f, 0x73, 0x69, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x50, 0x72, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x6e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x50, 0x72, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x68, 0x69, 0x66,
	0x74, 0x49, 0x64, 0x18, 0x78, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x53, 0x68, 0x69, 0x66, 0x74,
	0x49, 0x64, 0x22, 0x8f, 0x01, 0x0a, 0x0c, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x4f, 0x66, 0x66,
	0x69, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x14, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x66, 0x66, 0x69, 0x63, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x1e,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03,
	0x70, 0x69, 0x64, 0x18, 0x28, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x69, 0x64, 0x12, 0x24,
	0x0a, 0x06, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x32, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x06, 0x44, 0x6f,
	0x63, 0x74, 0x6f, 0x72, 0x22, 0x9a, 0x02, 0x0a, 0x06, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1f, 0x0a, 0x0b, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x14,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x1e, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61,
	0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x78, 0x18, 0x28, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x73, 0x65, 0x78, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x32, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x3c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74,
	0x61, 0x67, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x46, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x61, 0x67, 0x65,
	0x18, 0x50, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x77, 0x6f, 0x72, 0x6b, 0x41, 0x67, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x5a, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x77, 0x6f, 0x72, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x6f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x64, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x6f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x6e, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x22, 0xad, 0x01, 0x0a, 0x0b, 0x53, 0x68, 0x69, 0x66, 0x74, 0x44, 0x6f, 0x63, 0x74, 0x6f,
	0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x14,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x1e, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x28, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x32, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x3c, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x46, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x32, 0xc7, 0x05, 0x0a, 0x0d, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x3c, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x1a, 0x0b, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x12, 0x54, 0x0a, 0x1d, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x41, 0x70, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x26, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c,
	0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x0b, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x4e, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x41, 0x70,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x64, 0x12, 0x1b, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d,
	0x65, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74,
	0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x12, 0x84, 0x01, 0x0a, 0x24, 0x47, 0x65, 0x74, 0x41,
	0x74, 0x74, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x68, 0x79, 0x73, 0x69, 0x63, 0x69, 0x61,
	0x6e, 0x42, 0x79, 0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x12, 0x2d, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x74, 0x74, 0x65, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x50, 0x68, 0x79, 0x73, 0x69, 0x63, 0x69, 0x61, 0x6e, 0x42, 0x79, 0x41,
	0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x52, 0x65, 0x71, 0x1a,
	0x2d, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x74, 0x74, 0x65, 0x6e, 0x64,
	0x69, 0x6e, 0x67, 0x50, 0x68, 0x79, 0x73, 0x69, 0x63, 0x69, 0x61, 0x6e, 0x42, 0x79, 0x41, 0x70,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x52, 0x65, 0x73, 0x12, 0x75,
	0x0a, 0x1f, 0x47, 0x65, 0x74, 0x41, 0x74, 0x74, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x68,
	0x79, 0x73, 0x69, 0x63, 0x69, 0x61, 0x6e, 0x42, 0x79, 0x49, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x12, 0x28, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x74, 0x74, 0x65,
	0x6e, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x68, 0x79, 0x73, 0x69, 0x63, 0x69, 0x61, 0x6e, 0x42, 0x79,
	0x49, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x28, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x74, 0x74, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x50,
	0x68, 0x79, 0x73, 0x69, 0x63, 0x69, 0x61, 0x6e, 0x42, 0x79, 0x49, 0x64, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x2e, 0x0a, 0x0a, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x0b, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x13, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x63, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x4f, 0x66, 0x66, 0x69,
	0x63, 0x65, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x49, 0x64,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x21, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x4f, 0x66, 0x66, 0x69,
	0x63, 0x65, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x49, 0x64,
	0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x21, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x4f,
	0x66, 0x66, 0x69, 0x63, 0x65, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x42,
	0x79, 0x49, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x12, 0x3f, 0x0a, 0x0d, 0x44, 0x6f,
	0x63, 0x74, 0x6f, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x16, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x2e, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73,
	0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x44, 0x6f, 0x63, 0x74, 0x6f,
	0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x42, 0x09, 0x5a, 0x07, 0x2e,
	0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_doc_registeration_proto_rawDescOnce sync.Once
	file_rpc_doc_registeration_proto_rawDescData = file_rpc_doc_registeration_proto_rawDesc
)

func file_rpc_doc_registeration_proto_rawDescGZIP() []byte {
	file_rpc_doc_registeration_proto_rawDescOnce.Do(func() {
		file_rpc_doc_registeration_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_doc_registeration_proto_rawDescData)
	})
	return file_rpc_doc_registeration_proto_rawDescData
}

var file_rpc_doc_registeration_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_rpc_doc_registeration_proto_goTypes = []interface{}{
	(*Empty)(nil),                                   // 0: user.Empty
	(*CreateAppointmentReq)(nil),                    // 1: user.CreateAppointmentReq
	(*CancelAppointmentRegistrationReq)(nil),        // 2: user.CancelAppointmentRegistrationReq
	(*GetAppointmentByIdReq)(nil),                   // 3: user.GetAppointmentByIdReq
	(*GetAppointmentByIdRes)(nil),                   // 4: user.GetAppointmentByIdRes
	(*GetAttendingPhysicianByAppointmentIdReq)(nil), // 5: user.GetAttendingPhysicianByAppointmentIdReq
	(*GetAttendingPhysicianByAppointmentIdRes)(nil), // 6: user.GetAttendingPhysicianByAppointmentIdRes
	(*GetAttendingPhysicianByIdNumberReq)(nil),      // 7: user.GetAttendingPhysicianByIdNumberReq
	(*GetAttendingPhysicianByIdNumberRes)(nil),      // 8: user.GetAttendingPhysicianByIdNumberRes
	(*OfficeListRes)(nil),                           // 9: user.OfficeListRes
	(*OfficeDoctorListByIdTimeReq)(nil),             // 10: user.OfficeDoctorListByIdTimeReq
	(*OfficeDoctorListByIdTimeRes)(nil),             // 11: user.OfficeDoctorListByIdTimeRes
	(*DoctorDetailsReq)(nil),                        // 12: user.DoctorDetailsReq
	(*DoctorDetailsRes)(nil),                        // 13: user.DoctorDetailsRes
	(*Appointment)(nil),                             // 14: user.Appointment
	(*AttendingPhysician)(nil),                      // 15: user.AttendingPhysician
	(*DoctorOffice)(nil),                            // 16: user.DoctorOffice
	(*Doctor)(nil),                                  // 17: user.Doctor
	(*ShiftDoctor)(nil),                             // 18: user.ShiftDoctor
}
var file_rpc_doc_registeration_proto_depIdxs = []int32{
	14, // 0: user.GetAppointmentByIdRes.data:type_name -> user.Appointment
	15, // 1: user.GetAttendingPhysicianByAppointmentIdRes.data:type_name -> user.AttendingPhysician
	15, // 2: user.GetAttendingPhysicianByIdNumberRes.data:type_name -> user.AttendingPhysician
	16, // 3: user.OfficeListRes.data:type_name -> user.DoctorOffice
	18, // 4: user.OfficeDoctorListByIdTimeRes.data:type_name -> user.ShiftDoctor
	17, // 5: user.DoctorDetailsRes.data:type_name -> user.Doctor
	17, // 6: user.DoctorOffice.Doctor:type_name -> user.Doctor
	1,  // 7: user.Registeration.CreateAppointment:input_type -> user.CreateAppointmentReq
	2,  // 8: user.Registeration.CancelAppointmentRegistration:input_type -> user.CancelAppointmentRegistrationReq
	3,  // 9: user.Registeration.GetAppointmentById:input_type -> user.GetAppointmentByIdReq
	5,  // 10: user.Registeration.GetAttendingPhysicianByAppointmentId:input_type -> user.GetAttendingPhysicianByAppointmentIdReq
	7,  // 11: user.Registeration.GetAttendingPhysicianByIdNumber:input_type -> user.GetAttendingPhysicianByIdNumberReq
	0,  // 12: user.Registeration.OfficeList:input_type -> user.Empty
	10, // 13: user.Registeration.GetOfficeDoctorListByIdTime:input_type -> user.OfficeDoctorListByIdTimeReq
	12, // 14: user.Registeration.DoctorDetails:input_type -> user.DoctorDetailsReq
	0,  // 15: user.Registeration.CreateAppointment:output_type -> user.Empty
	0,  // 16: user.Registeration.CancelAppointmentRegistration:output_type -> user.Empty
	4,  // 17: user.Registeration.GetAppointmentById:output_type -> user.GetAppointmentByIdRes
	6,  // 18: user.Registeration.GetAttendingPhysicianByAppointmentId:output_type -> user.GetAttendingPhysicianByAppointmentIdRes
	8,  // 19: user.Registeration.GetAttendingPhysicianByIdNumber:output_type -> user.GetAttendingPhysicianByIdNumberRes
	9,  // 20: user.Registeration.OfficeList:output_type -> user.OfficeListRes
	11, // 21: user.Registeration.GetOfficeDoctorListByIdTime:output_type -> user.OfficeDoctorListByIdTimeRes
	13, // 22: user.Registeration.DoctorDetails:output_type -> user.DoctorDetailsRes
	15, // [15:23] is the sub-list for method output_type
	7,  // [7:15] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_rpc_doc_registeration_proto_init() }
func file_rpc_doc_registeration_proto_init() {
	if File_rpc_doc_registeration_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_doc_registeration_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_doc_registeration_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAppointmentReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_doc_registeration_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelAppointmentRegistrationReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_doc_registeration_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAppointmentByIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_doc_registeration_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAppointmentByIdRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_doc_registeration_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAttendingPhysicianByAppointmentIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_doc_registeration_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAttendingPhysicianByAppointmentIdRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_doc_registeration_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAttendingPhysicianByIdNumberReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_doc_registeration_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAttendingPhysicianByIdNumberRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_doc_registeration_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OfficeListRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_doc_registeration_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OfficeDoctorListByIdTimeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_doc_registeration_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OfficeDoctorListByIdTimeRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_doc_registeration_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoctorDetailsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_doc_registeration_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoctorDetailsRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_doc_registeration_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Appointment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_doc_registeration_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttendingPhysician); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_doc_registeration_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoctorOffice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_doc_registeration_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Doctor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_doc_registeration_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShiftDoctor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_doc_registeration_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_doc_registeration_proto_goTypes,
		DependencyIndexes: file_rpc_doc_registeration_proto_depIdxs,
		MessageInfos:      file_rpc_doc_registeration_proto_msgTypes,
	}.Build()
	File_rpc_doc_registeration_proto = out.File
	file_rpc_doc_registeration_proto_rawDesc = nil
	file_rpc_doc_registeration_proto_goTypes = nil
	file_rpc_doc_registeration_proto_depIdxs = nil
}
