// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.4
// source: rpc/doc/registeration.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 预约  增删改查
type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_doc_registeration_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_doc_registeration_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_rpc_doc_registeration_proto_rawDescGZIP(), []int{0}
}

// 预约
type AppointmentAttendingPhysicianReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId          int32  `protobuf:"varint,10,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DoctorId        int32  `protobuf:"varint,20,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	RealName        string `protobuf:"bytes,30,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	IdNumber        string `protobuf:"bytes,40,opt,name=id_number,json=idNumber,proto3" json:"id_number,omitempty"`
	Mobile          string `protobuf:"bytes,50,opt,name=mobile,proto3" json:"mobile,omitempty"`
	AppointmentData string `protobuf:"bytes,60,opt,name=appointment_data,json=appointmentData,proto3" json:"appointment_data,omitempty"`
	AppointmentType int32  `protobuf:"varint,70,opt,name=appointment_type,json=appointmentType,proto3" json:"appointment_type,omitempty"`
	OfficeId        int32  `protobuf:"varint,80,opt,name=office_id,json=officeId,proto3" json:"office_id,omitempty"`
	Status          int32  `protobuf:"varint,90,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *AppointmentAttendingPhysicianReq) Reset() {
	*x = AppointmentAttendingPhysicianReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_doc_registeration_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppointmentAttendingPhysicianReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppointmentAttendingPhysicianReq) ProtoMessage() {}

func (x *AppointmentAttendingPhysicianReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_doc_registeration_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppointmentAttendingPhysicianReq.ProtoReflect.Descriptor instead.
func (*AppointmentAttendingPhysicianReq) Descriptor() ([]byte, []int) {
	return file_rpc_doc_registeration_proto_rawDescGZIP(), []int{1}
}

func (x *AppointmentAttendingPhysicianReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AppointmentAttendingPhysicianReq) GetDoctorId() int32 {
	if x != nil {
		return x.DoctorId
	}
	return 0
}

func (x *AppointmentAttendingPhysicianReq) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *AppointmentAttendingPhysicianReq) GetIdNumber() string {
	if x != nil {
		return x.IdNumber
	}
	return ""
}

func (x *AppointmentAttendingPhysicianReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *AppointmentAttendingPhysicianReq) GetAppointmentData() string {
	if x != nil {
		return x.AppointmentData
	}
	return ""
}

func (x *AppointmentAttendingPhysicianReq) GetAppointmentType() int32 {
	if x != nil {
		return x.AppointmentType
	}
	return 0
}

func (x *AppointmentAttendingPhysicianReq) GetOfficeId() int32 {
	if x != nil {
		return x.OfficeId
	}
	return 0
}

func (x *AppointmentAttendingPhysicianReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 取消预约
type CancelAppointmentRegistrationReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppointmentId int32 `protobuf:"varint,1,opt,name=appointment_id,json=appointmentId,proto3" json:"appointment_id,omitempty"`
}

func (x *CancelAppointmentRegistrationReq) Reset() {
	*x = CancelAppointmentRegistrationReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_doc_registeration_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelAppointmentRegistrationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelAppointmentRegistrationReq) ProtoMessage() {}

func (x *CancelAppointmentRegistrationReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_doc_registeration_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelAppointmentRegistrationReq.ProtoReflect.Descriptor instead.
func (*CancelAppointmentRegistrationReq) Descriptor() ([]byte, []int) {
	return file_rpc_doc_registeration_proto_rawDescGZIP(), []int{2}
}

func (x *CancelAppointmentRegistrationReq) GetAppointmentId() int32 {
	if x != nil {
		return x.AppointmentId
	}
	return 0
}

// 获取预约信息
type GetAppointmentRegistrationByIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AttendingPhysicianId int32 `protobuf:"varint,1,opt,name=attending_physician_id,json=attendingPhysicianId,proto3" json:"attending_physician_id,omitempty"`
}

func (x *GetAppointmentRegistrationByIdReq) Reset() {
	*x = GetAppointmentRegistrationByIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_doc_registeration_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAppointmentRegistrationByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppointmentRegistrationByIdReq) ProtoMessage() {}

func (x *GetAppointmentRegistrationByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_doc_registeration_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppointmentRegistrationByIdReq.ProtoReflect.Descriptor instead.
func (*GetAppointmentRegistrationByIdReq) Descriptor() ([]byte, []int) {
	return file_rpc_doc_registeration_proto_rawDescGZIP(), []int{3}
}

func (x *GetAppointmentRegistrationByIdReq) GetAttendingPhysicianId() int32 {
	if x != nil {
		return x.AttendingPhysicianId
	}
	return 0
}

type GetAppointmentRegistrationByIdRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *AttendingPhysician `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetAppointmentRegistrationByIdRes) Reset() {
	*x = GetAppointmentRegistrationByIdRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_doc_registeration_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAppointmentRegistrationByIdRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppointmentRegistrationByIdRes) ProtoMessage() {}

func (x *GetAppointmentRegistrationByIdRes) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_doc_registeration_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppointmentRegistrationByIdRes.ProtoReflect.Descriptor instead.
func (*GetAppointmentRegistrationByIdRes) Descriptor() ([]byte, []int) {
	return file_rpc_doc_registeration_proto_rawDescGZIP(), []int{4}
}

func (x *GetAppointmentRegistrationByIdRes) GetData() *AttendingPhysician {
	if x != nil {
		return x.Data
	}
	return nil
}

// 用户预约结构体
type AppointmentRegistration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId          int32  `protobuf:"varint,10,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AppointmentType int32  `protobuf:"varint,20,opt,name=AppointmentType,proto3" json:"AppointmentType,omitempty"`
	AppointmentDate string `protobuf:"bytes,40,opt,name=AppointmentDate,proto3" json:"AppointmentDate,omitempty"`
	AppointmentTime string `protobuf:"bytes,50,opt,name=AppointmentTime,proto3" json:"AppointmentTime,omitempty"`
	Status          int32  `protobuf:"varint,60,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *AppointmentRegistration) Reset() {
	*x = AppointmentRegistration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_doc_registeration_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppointmentRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppointmentRegistration) ProtoMessage() {}

func (x *AppointmentRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_doc_registeration_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppointmentRegistration.ProtoReflect.Descriptor instead.
func (*AppointmentRegistration) Descriptor() ([]byte, []int) {
	return file_rpc_doc_registeration_proto_rawDescGZIP(), []int{5}
}

func (x *AppointmentRegistration) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AppointmentRegistration) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AppointmentRegistration) GetAppointmentType() int32 {
	if x != nil {
		return x.AppointmentType
	}
	return 0
}

func (x *AppointmentRegistration) GetAppointmentDate() string {
	if x != nil {
		return x.AppointmentDate
	}
	return ""
}

func (x *AppointmentRegistration) GetAppointmentTime() string {
	if x != nil {
		return x.AppointmentTime
	}
	return ""
}

func (x *AppointmentRegistration) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 用户挂号
type AttendingPhysician struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int32  `protobuf:"varint,10,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32  `protobuf:"varint,20,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AppointmentId int32  `protobuf:"varint,30,opt,name=appointment_id,json=appointmentId,proto3" json:"appointment_id,omitempty"`
	DoctorID      int32  `protobuf:"varint,40,opt,name=DoctorID,proto3" json:"DoctorID,omitempty"`
	OfficeID      int32  `protobuf:"varint,50,opt,name=OfficeID,proto3" json:"OfficeID,omitempty"`
	RealName      string `protobuf:"bytes,60,opt,name=RealName,proto3" json:"RealName,omitempty"`
	IDNumber      string `protobuf:"bytes,80,opt,name=IDNumber,proto3" json:"IDNumber,omitempty"`
	Symptoms      string `protobuf:"bytes,90,opt,name=Symptoms,proto3" json:"Symptoms,omitempty"`
	Diagnosis     string `protobuf:"bytes,100,opt,name=Diagnosis,proto3" json:"Diagnosis,omitempty"`
	Prescription  string `protobuf:"bytes,110,opt,name=Prescription,proto3" json:"Prescription,omitempty"`
}

func (x *AttendingPhysician) Reset() {
	*x = AttendingPhysician{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_doc_registeration_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttendingPhysician) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttendingPhysician) ProtoMessage() {}

func (x *AttendingPhysician) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_doc_registeration_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttendingPhysician.ProtoReflect.Descriptor instead.
func (*AttendingPhysician) Descriptor() ([]byte, []int) {
	return file_rpc_doc_registeration_proto_rawDescGZIP(), []int{6}
}

func (x *AttendingPhysician) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AttendingPhysician) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AttendingPhysician) GetAppointmentId() int32 {
	if x != nil {
		return x.AppointmentId
	}
	return 0
}

func (x *AttendingPhysician) GetDoctorID() int32 {
	if x != nil {
		return x.DoctorID
	}
	return 0
}

func (x *AttendingPhysician) GetOfficeID() int32 {
	if x != nil {
		return x.OfficeID
	}
	return 0
}

func (x *AttendingPhysician) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *AttendingPhysician) GetIDNumber() string {
	if x != nil {
		return x.IDNumber
	}
	return ""
}

func (x *AttendingPhysician) GetSymptoms() string {
	if x != nil {
		return x.Symptoms
	}
	return ""
}

func (x *AttendingPhysician) GetDiagnosis() string {
	if x != nil {
		return x.Diagnosis
	}
	return ""
}

func (x *AttendingPhysician) GetPrescription() string {
	if x != nil {
		return x.Prescription
	}
	return ""
}

// ------------------------------------------------//todo 医生模块--------------------------------------------------------
// 科室列表
type OfficeListRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*DoctorOffice `protobuf:"bytes,10,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *OfficeListRes) Reset() {
	*x = OfficeListRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_doc_registeration_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OfficeListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfficeListRes) ProtoMessage() {}

func (x *OfficeListRes) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_doc_registeration_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfficeListRes.ProtoReflect.Descriptor instead.
func (*OfficeListRes) Descriptor() ([]byte, []int) {
	return file_rpc_doc_registeration_proto_rawDescGZIP(), []int{7}
}

func (x *OfficeListRes) GetData() []*DoctorOffice {
	if x != nil {
		return x.Data
	}
	return nil
}

// 科室医生列表
type OfficeDoctorListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OfficeId int32 `protobuf:"varint,10,opt,name=office_id,json=officeId,proto3" json:"office_id,omitempty"`
}

func (x *OfficeDoctorListReq) Reset() {
	*x = OfficeDoctorListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_doc_registeration_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OfficeDoctorListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfficeDoctorListReq) ProtoMessage() {}

func (x *OfficeDoctorListReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_doc_registeration_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfficeDoctorListReq.ProtoReflect.Descriptor instead.
func (*OfficeDoctorListReq) Descriptor() ([]byte, []int) {
	return file_rpc_doc_registeration_proto_rawDescGZIP(), []int{8}
}

func (x *OfficeDoctorListReq) GetOfficeId() int32 {
	if x != nil {
		return x.OfficeId
	}
	return 0
}

type OfficeDoctorListRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *DoctorOffice `protobuf:"bytes,10,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *OfficeDoctorListRes) Reset() {
	*x = OfficeDoctorListRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_doc_registeration_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OfficeDoctorListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfficeDoctorListRes) ProtoMessage() {}

func (x *OfficeDoctorListRes) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_doc_registeration_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfficeDoctorListRes.ProtoReflect.Descriptor instead.
func (*OfficeDoctorListRes) Descriptor() ([]byte, []int) {
	return file_rpc_doc_registeration_proto_rawDescGZIP(), []int{9}
}

func (x *OfficeDoctorListRes) GetData() *DoctorOffice {
	if x != nil {
		return x.Data
	}
	return nil
}

// 医生详情
type DoctorDetailsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DoctorId int32 `protobuf:"varint,10,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
}

func (x *DoctorDetailsReq) Reset() {
	*x = DoctorDetailsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_doc_registeration_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoctorDetailsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorDetailsReq) ProtoMessage() {}

func (x *DoctorDetailsReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_doc_registeration_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorDetailsReq.ProtoReflect.Descriptor instead.
func (*DoctorDetailsReq) Descriptor() ([]byte, []int) {
	return file_rpc_doc_registeration_proto_rawDescGZIP(), []int{10}
}

func (x *DoctorDetailsReq) GetDoctorId() int32 {
	if x != nil {
		return x.DoctorId
	}
	return 0
}

type DoctorDetailsRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Doctor `protobuf:"bytes,10,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *DoctorDetailsRes) Reset() {
	*x = DoctorDetailsRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_doc_registeration_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoctorDetailsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorDetailsRes) ProtoMessage() {}

func (x *DoctorDetailsRes) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_doc_registeration_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorDetailsRes.ProtoReflect.Descriptor instead.
func (*DoctorDetailsRes) Descriptor() ([]byte, []int) {
	return file_rpc_doc_registeration_proto_rawDescGZIP(), []int{11}
}

func (x *DoctorDetailsRes) GetData() *Doctor {
	if x != nil {
		return x.Data
	}
	return nil
}

// 科室
type DoctorOffice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int32     `protobuf:"varint,10,opt,name=id,proto3" json:"id,omitempty"`
	OfficeName string    `protobuf:"bytes,20,opt,name=office_name,json=officeName,proto3" json:"office_name,omitempty"`
	Status     int32     `protobuf:"varint,30,opt,name=status,proto3" json:"status,omitempty"`
	Doctor     []*Doctor `protobuf:"bytes,40,rep,name=Doctor,proto3" json:"Doctor,omitempty"`
}

func (x *DoctorOffice) Reset() {
	*x = DoctorOffice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_doc_registeration_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoctorOffice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorOffice) ProtoMessage() {}

func (x *DoctorOffice) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_doc_registeration_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorOffice.ProtoReflect.Descriptor instead.
func (*DoctorOffice) Descriptor() ([]byte, []int) {
	return file_rpc_doc_registeration_proto_rawDescGZIP(), []int{12}
}

func (x *DoctorOffice) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DoctorOffice) GetOfficeName() string {
	if x != nil {
		return x.OfficeName
	}
	return ""
}

func (x *DoctorOffice) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DoctorOffice) GetDoctor() []*Doctor {
	if x != nil {
		return x.Doctor
	}
	return nil
}

// 医生
type Doctor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int32  `protobuf:"varint,10,opt,name=id,proto3" json:"id,omitempty"`
	DoctorName  string `protobuf:"bytes,20,opt,name=doctor_name,json=doctorName,proto3" json:"doctor_name,omitempty"`
	Age         int32  `protobuf:"varint,30,opt,name=age,proto3" json:"age,omitempty"`
	Sex         int32  `protobuf:"varint,40,opt,name=sex,proto3" json:"sex,omitempty"`
	Position    string `protobuf:"bytes,50,opt,name=position,proto3" json:"position,omitempty"`
	Tag         string `protobuf:"bytes,60,opt,name=tag,proto3" json:"tag,omitempty"`
	Description string `protobuf:"bytes,70,opt,name=description,proto3" json:"description,omitempty"`
	WorkAge     int32  `protobuf:"varint,80,opt,name=work_age,json=workAge,proto3" json:"work_age,omitempty"`
	WorkTime    string `protobuf:"bytes,90,opt,name=work_time,json=workTime,proto3" json:"work_time,omitempty"`
	OfficeId    int32  `protobuf:"varint,100,opt,name=office_id,json=officeId,proto3" json:"office_id,omitempty"`
	Status      int32  `protobuf:"varint,110,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *Doctor) Reset() {
	*x = Doctor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_doc_registeration_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Doctor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Doctor) ProtoMessage() {}

func (x *Doctor) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_doc_registeration_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Doctor.ProtoReflect.Descriptor instead.
func (*Doctor) Descriptor() ([]byte, []int) {
	return file_rpc_doc_registeration_proto_rawDescGZIP(), []int{13}
}

func (x *Doctor) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Doctor) GetDoctorName() string {
	if x != nil {
		return x.DoctorName
	}
	return ""
}

func (x *Doctor) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Doctor) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *Doctor) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *Doctor) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Doctor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Doctor) GetWorkAge() int32 {
	if x != nil {
		return x.WorkAge
	}
	return 0
}

func (x *Doctor) GetWorkTime() string {
	if x != nil {
		return x.WorkTime
	}
	return ""
}

func (x *Doctor) GetOfficeId() int32 {
	if x != nil {
		return x.OfficeId
	}
	return 0
}

func (x *Doctor) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_rpc_doc_registeration_proto protoreflect.FileDescriptor

var file_rpc_doc_registeration_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x72, 0x70, 0x63, 0x2f, 0x64, 0x6f, 0x63, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0xb5, 0x02, 0x0a,
	0x20, 0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x74, 0x74, 0x65,
	0x6e, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x68, 0x79, 0x73, 0x69, 0x63, 0x69, 0x61, 0x6e, 0x52, 0x65,
	0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x6f,
	0x63, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x14, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64,
	0x6f, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x61, 0x6c, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x1e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x61, 0x6c,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x64, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x28, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x32, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x61, 0x70, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x3c, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0f, 0x61, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x29, 0x0a, 0x10, 0x61, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d,
	0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x46, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f,
	0x61, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x6f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x50, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x6f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x5a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0x49, 0x0a, 0x20, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x41, 0x70,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x70, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0d, 0x61, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22,
	0x59, 0x0a, 0x21, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x79, 0x49,
	0x64, 0x52, 0x65, 0x71, 0x12, 0x34, 0x0a, 0x16, 0x61, 0x74, 0x74, 0x65, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x5f, 0x70, 0x68, 0x79, 0x73, 0x69, 0x63, 0x69, 0x61, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x14, 0x61, 0x74, 0x74, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x50,
	0x68, 0x79, 0x73, 0x69, 0x63, 0x69, 0x61, 0x6e, 0x49, 0x64, 0x22, 0x51, 0x0a, 0x21, 0x47, 0x65,
	0x74, 0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x12,
	0x2c, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x2e, 0x41, 0x74, 0x74, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x68,
	0x79, 0x73, 0x69, 0x63, 0x69, 0x61, 0x6e, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xd8, 0x01,
	0x0a, 0x17, 0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x14, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x41, 0x70, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x28, 0x0a, 0x0f,
	0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x65, 0x18,
	0x28, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65,
	0x6e, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x32, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0f, 0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x3c, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xb2, 0x02, 0x0a, 0x12, 0x41, 0x74, 0x74,
	0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x68, 0x79, 0x73, 0x69, 0x63, 0x69, 0x61, 0x6e, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x14, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x70, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x1e, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0d, 0x61, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x44, 0x18, 0x28, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x4f,
	0x66, 0x66, 0x69, 0x63, 0x65, 0x49, 0x44, 0x18, 0x32, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x4f,
	0x66, 0x66, 0x69, 0x63, 0x65, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x61, 0x6c, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x3c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x52, 0x65, 0x61, 0x6c, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x49, 0x44, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x50, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x49, 0x44, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x1a, 0x0a, 0x08, 0x53, 0x79, 0x6d, 0x70, 0x74, 0x6f, 0x6d, 0x73, 0x18, 0x5a, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x53, 0x79, 0x6d, 0x70, 0x74, 0x6f, 0x6d, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x44,
	0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x18, 0x64, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x50, 0x72, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x6e, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x50, 0x72, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x37, 0x0a,
	0x0d, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x26,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x2e, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x65,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x32, 0x0a, 0x13, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x65,
	0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a,
	0x09, 0x6f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x6f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x49, 0x64, 0x22, 0x3d, 0x0a, 0x13, 0x4f, 0x66,
	0x66, 0x69, 0x63, 0x65, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x12, 0x26, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x4f, 0x66, 0x66,
	0x69, 0x63, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x2f, 0x0a, 0x10, 0x44, 0x6f, 0x63,
	0x74, 0x6f, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a,
	0x09, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x22, 0x34, 0x0a, 0x10, 0x44, 0x6f,
	0x63, 0x74, 0x6f, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x12, 0x20,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x2e, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x7d, 0x0a, 0x0c, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x14, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x1e, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x24, 0x0a, 0x06, 0x44, 0x6f, 0x63,
	0x74, 0x6f, 0x72, 0x18, 0x28, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x06, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x22,
	0x9a, 0x02, 0x0a, 0x06, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x6f,
	0x63, 0x74, 0x6f, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x14, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61,
	0x67, 0x65, 0x18, 0x1e, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x73, 0x65, 0x78, 0x18, 0x28, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x65, 0x78, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x32, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x74,
	0x61, 0x67, 0x18, 0x3c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x46, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x19, 0x0a, 0x08, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x61, 0x67, 0x65, 0x18, 0x50, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x77, 0x6f, 0x72, 0x6b, 0x41, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x77, 0x6f,
	0x72, 0x6b, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x5a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x77,
	0x6f, 0x72, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6f, 0x66, 0x66, 0x69, 0x63,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x64, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6f, 0x66, 0x66, 0x69,
	0x63, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x6e,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0xea, 0x03, 0x0a,
	0x0d, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x54,
	0x0a, 0x1d, 0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x74, 0x74,
	0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x68, 0x79, 0x73, 0x69, 0x63, 0x69, 0x61, 0x6e, 0x12,
	0x26, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65,
	0x6e, 0x74, 0x41, 0x74, 0x74, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x68, 0x79, 0x73, 0x69,
	0x63, 0x69, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x0b, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x12, 0x54, 0x0a, 0x1d, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x41, 0x70,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x43, 0x61, 0x6e,
	0x63, 0x65, 0x6c, 0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x0b, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x72, 0x0a, 0x1e, 0x47, 0x65,
	0x74, 0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x79, 0x49, 0x64, 0x12, 0x27, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x79,
	0x49, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x27, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74,
	0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x12, 0x2e,
	0x0a, 0x0a, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x0b, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x13, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x48,
	0x0a, 0x10, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x19, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x65,
	0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x2e, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x44, 0x6f, 0x63, 0x74, 0x6f,
	0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x3f, 0x0a, 0x0d, 0x44, 0x6f, 0x63, 0x74,
	0x6f, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x16, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65,
	0x71, 0x1a, 0x16, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_doc_registeration_proto_rawDescOnce sync.Once
	file_rpc_doc_registeration_proto_rawDescData = file_rpc_doc_registeration_proto_rawDesc
)

func file_rpc_doc_registeration_proto_rawDescGZIP() []byte {
	file_rpc_doc_registeration_proto_rawDescOnce.Do(func() {
		file_rpc_doc_registeration_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_doc_registeration_proto_rawDescData)
	})
	return file_rpc_doc_registeration_proto_rawDescData
}

var file_rpc_doc_registeration_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_rpc_doc_registeration_proto_goTypes = []interface{}{
	(*Empty)(nil),                             // 0: user.Empty
	(*AppointmentAttendingPhysicianReq)(nil),  // 1: user.AppointmentAttendingPhysicianReq
	(*CancelAppointmentRegistrationReq)(nil),  // 2: user.CancelAppointmentRegistrationReq
	(*GetAppointmentRegistrationByIdReq)(nil), // 3: user.GetAppointmentRegistrationByIdReq
	(*GetAppointmentRegistrationByIdRes)(nil), // 4: user.GetAppointmentRegistrationByIdRes
	(*AppointmentRegistration)(nil),           // 5: user.AppointmentRegistration
	(*AttendingPhysician)(nil),                // 6: user.AttendingPhysician
	(*OfficeListRes)(nil),                     // 7: user.OfficeListRes
	(*OfficeDoctorListReq)(nil),               // 8: user.OfficeDoctorListReq
	(*OfficeDoctorListRes)(nil),               // 9: user.OfficeDoctorListRes
	(*DoctorDetailsReq)(nil),                  // 10: user.DoctorDetailsReq
	(*DoctorDetailsRes)(nil),                  // 11: user.DoctorDetailsRes
	(*DoctorOffice)(nil),                      // 12: user.DoctorOffice
	(*Doctor)(nil),                            // 13: user.Doctor
}
var file_rpc_doc_registeration_proto_depIdxs = []int32{
	6,  // 0: user.GetAppointmentRegistrationByIdRes.data:type_name -> user.AttendingPhysician
	12, // 1: user.OfficeListRes.data:type_name -> user.DoctorOffice
	12, // 2: user.OfficeDoctorListRes.data:type_name -> user.DoctorOffice
	13, // 3: user.DoctorDetailsRes.data:type_name -> user.Doctor
	13, // 4: user.DoctorOffice.Doctor:type_name -> user.Doctor
	1,  // 5: user.Registeration.AppointmentAttendingPhysician:input_type -> user.AppointmentAttendingPhysicianReq
	2,  // 6: user.Registeration.CancelAppointmentRegistration:input_type -> user.CancelAppointmentRegistrationReq
	3,  // 7: user.Registeration.GetAppointmentRegistrationById:input_type -> user.GetAppointmentRegistrationByIdReq
	0,  // 8: user.Registeration.OfficeList:input_type -> user.Empty
	8,  // 9: user.Registeration.OfficeDoctorList:input_type -> user.OfficeDoctorListReq
	10, // 10: user.Registeration.DoctorDetails:input_type -> user.DoctorDetailsReq
	0,  // 11: user.Registeration.AppointmentAttendingPhysician:output_type -> user.Empty
	0,  // 12: user.Registeration.CancelAppointmentRegistration:output_type -> user.Empty
	4,  // 13: user.Registeration.GetAppointmentRegistrationById:output_type -> user.GetAppointmentRegistrationByIdRes
	7,  // 14: user.Registeration.OfficeList:output_type -> user.OfficeListRes
	9,  // 15: user.Registeration.OfficeDoctorList:output_type -> user.OfficeDoctorListRes
	11, // 16: user.Registeration.DoctorDetails:output_type -> user.DoctorDetailsRes
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_rpc_doc_registeration_proto_init() }
func file_rpc_doc_registeration_proto_init() {
	if File_rpc_doc_registeration_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_doc_registeration_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_doc_registeration_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppointmentAttendingPhysicianReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_doc_registeration_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelAppointmentRegistrationReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_doc_registeration_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAppointmentRegistrationByIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_doc_registeration_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAppointmentRegistrationByIdRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_doc_registeration_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppointmentRegistration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_doc_registeration_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttendingPhysician); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_doc_registeration_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OfficeListRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_doc_registeration_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OfficeDoctorListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_doc_registeration_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OfficeDoctorListRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_doc_registeration_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoctorDetailsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_doc_registeration_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoctorDetailsRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_doc_registeration_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoctorOffice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_doc_registeration_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Doctor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_doc_registeration_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_doc_registeration_proto_goTypes,
		DependencyIndexes: file_rpc_doc_registeration_proto_depIdxs,
		MessageInfos:      file_rpc_doc_registeration_proto_msgTypes,
	}.Build()
	File_rpc_doc_registeration_proto = out.File
	file_rpc_doc_registeration_proto_rawDesc = nil
	file_rpc_doc_registeration_proto_goTypes = nil
	file_rpc_doc_registeration_proto_depIdxs = nil
}
